name: Publish Docker image

on:  
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      input_version:
        description: "Version to publish"
        required: true
        
env:
  versionNumber: ${{ github.event.release.tag_name || github.event.inputs.input_version }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lowercase repository name
      run: |
        echo "LOWER_REPO=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
    - name: Get repository name without owner
      run: |
        echo "JUST_REPO_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV      
      shell: bash
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.DOCKER_USER }}/${{ env.JUST_REPO_NAME }}:${{ env.versionNumber }}
    - name: Push to Docker Hub
      run: docker push ${{ env.DOCKER_USER }}/${{ env.JUST_REPO_NAME }}:${{ env.versionNumber }}
