name: Publish Docker image

on:  
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      input_version:
        description: "Version to publish"
        required: true
        
env:
  VERSION_NUMBER: ${{ github.event.release.tag_name || github.event.inputs.input_version }}
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lowercase repository name
      run: |
        echo "LOWER_REPO=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
    - name: Get repository name without owner
      run: |
        echo "JUST_REPO_NAME=$(echo '${{ env.LOWER_REPO }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV      
      shell: bash
    - name: Login to Docker Hub
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag builtimage
    - name: Push version tag to Docker Hub
      run: |
        IMAGE_NAME=${{ env.DOCKER_USER }}/${{ env.JUST_REPO_NAME }}:${{ env.VERSION_NUMBER }}
        docker image tag builtimage $IMAGE_NAME
        docker push $IMAGE_NAME
    - name: Push latest tag to Docker Hub
      run: |
        IMAGE_NAME=${{ env.DOCKER_USER }}/${{ env.JUST_REPO_NAME }}:latest
        docker image tag builtimage $IMAGE_NAME
        docker push $IMAGE_NAME
