name: Publish Docker image

on:  
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      input_version:
        description: "Version to publish"
        required: true
        
env:
  versionNumber: ${{ github.event.release.tag_name || github.event.inputs.input_version }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lowercase repository name
      run: |
        echo "LOWER_REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.LOWER_REPO }}:${{ env.versionNumber }}
    - name: Push to Docker Hub
      run: docker push ${{ env.LOWER_REPO }}:${{ env.versionNumber }}
